spring:
  datasource: # 数据库链接
    url: jdbc:mysql://127.0.0.1:3306/kettle-scheduler?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true # sql打印
    database-platform: org.hibernate.dialect.MySQLDialect # 数据库方言
    open-in-view: false # false关闭懒加载
logging: # 日志记录
  config: classpath:log/logback.xml
  file: /apps/logs/${spring.application.name}/${spring.application.name}
  level:
    root: info
    org.kettle.scheduler: info
